const action_key = {
  ADD_TO_CART: "ADD_TO_CART",
  UPDATE_PRODUCT_STOCK: 'UPDATE_PRODUCT_STOCK',
  PERSIST_CART: 'PERSIST_CART',
  UPDATE_CART_QUANTITY: 'UPDATE_CART_QUANTITY',
  CLEAR_CART: "CLEAR_CART",
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  FETCH_DETAIL_PRODUCT: "FETCH_DETAIL_PRODUCT",
  FILTER_PRODUCT: "FILTER_PRODUCT",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  EMPTY_CART: "EMPTY_CART",
  SET_LOADING: "SET_LOADING",
  SET_ERROR: "SET_ERROR",
  SET_STOCK: 'SET_STOCK',
};

export default action_key;
