const action_key = {
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  FETCH_DETAIL_PRODUCT: "FETCH_DETAIL_PRODUCT",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  EMPTY_CART: "EMPTY_CART",
  FILTER_PRODUCT: "FILTER_PRODUCT",
  SET_LOADING: "SET_LOADING",
  SET_ERROR: "SET_ERROR",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  UPDATE_CART_ITEM: "UPDATE_CART_ITEM",
  CLEAR_CART: "CLEAR_CART",
  UPDATE_CART_QUANTITY: "UPDATE_CART_QUANTITY",
};

export default action_key;
